version: '3'

services:
  csv:
    image: "infracloudio/csvserver"
    env_file:
      - ./env
    volumes:
      - ./inputFile:/csvserver/inputdata
    container_name:
        "csvserver"
    ports:
      - "9393:9300"
  prom:
    image: "prom/prometheus:v2.22.0"
    container_name:
         "prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
